base_url = "https://blog.tristanbony.me"

title = "Tristan's Bytes"
description = "Yet another blog. Writing about everything and nothing. Vague, isn't it? Well, welcome anyway!"

theme = "apollo"
taxonomies = [{ name = "tags"}]

compile_sass = true
build_search_index = true
generate_feeds = true
minify_html = true

[markdown]
highlight_code = true
highlight_theme = "one-dark"

[search]
include_title = true
inclde_-description = true
include_date = true
include_path = false
include_content = true

[extra]
theme = "toggle"
socials = [
    { name = "mastodon", url = "https://floss.social/@TristanB0", icon = "mastodon" },
    { name = "rss", url = "https://blog.tristanbony.me/atom.xml", icon = "rss" },
]
menu = [
    { name = "/posts", url = "/posts", weight = 1 },
    { name = "/tags", url = "/tags", weight = 2 },
]
favicon = "favicon.svg"
stylesheets = [
    "custom.css"
]
mathjax = true
mathjax_dollar_inline_enable = true
toc = true
fancy_code = true
